version: '3.8'

services:
  web:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: curl --fail http://localhost:8000 || exit 1
      interval: 10s
      timeout: 10s
      start_period: 10s
      retries: 3
